version: '3.8'

services:
  api:
    build: .
    container_name: api-back
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - EXTERNAL_API_URL=https://api.rawg.io/api/games
      - API_KEY=${API_KEY}
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
